### ISSUE TITLE
Frontend doesn't seem to compile with typescript 2.4

### ISSUE THREAD

**Issue by PH111P** [SOSML/SOSML-frontend#9]
When trying to compile the frontend with some recent typescript, various errors are thrown; most of them are related to `require` constructs.

**Comment by crazyqnt** [comment]
Changed the typescript dependency of the frontend to 2.3.x the packages might need to be re-installed. Re-open if there are any issues.

**Comment by PH111P** [comment]
I don't think we should force ourselves to live with some old TypeScript version. Are there really any major issues with version 2.4.x that we cannot use it?

**Comment by crazyqnt** [comment]
The frontend now doesn't have a direct dependency on typescript anymore. Instead it now uses the `react-scripts-ts` wrapper directly.
